name: morsel_application_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  # '>=3.0.0-62.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.6
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  firebase_core: ^2.4.1
  intl: any

flutter:
  uses-material-design: true

  assets:
    - images/

# dependencies_overrides:
#   platform: ^3.1.0