// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpq42dUhwQM0UoRhMVBaxOHFFv_5bA_w',
    appId: '1:107133802687:web:fa6af13f92dbd8a1128e0a',
    messagingSenderId: '107133802687',
    projectId: 'morsel-38ae7',
    authDomain: 'morsel-38ae7.firebaseapp.com',
    storageBucket: 'morsel-38ae7.appspot.com',
    measurementId: 'G-VJX6EY2215',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1l8a7n1b7XQfYmwVst-UytFJfq2xJIA',
    appId: '1:107133802687:android:31033c6b6f775379128e0a',
    messagingSenderId: '107133802687',
    projectId: 'morsel-38ae7',
    storageBucket: 'morsel-38ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoArAZvrSmCEsRm_s6PwxvMY-4SFhEzSY',
    appId: '1:107133802687:ios:00d61456cea7939f128e0a',
    messagingSenderId: '107133802687',
    projectId: 'morsel-38ae7',
    storageBucket: 'morsel-38ae7.appspot.com',
    iosClientId: '107133802687-c6vm0qp61vg0f7uifnv755favjdf7ige.apps.googleusercontent.com',
    iosBundleId: 'com.example.morselApplication1',
  );
}
